# Generated by Django 3.2.8 on 2021-10-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pesan',
            new_name='message',
        ),
    ]
