<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-26 05:00
=======
# Generated by Django 3.2.8 on 2021-10-26 03:14
>>>>>>> ae6aeaa18dc82a0454d1a698bd046e54e1e1ad05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_login'),
        ('task', '0002_rename_pesan_message'),
    ]

    operations = [
    ]
