# Generated by Django 3.2.8 on 2021-10-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_login'),
        ('task', '0002_rename_pesan_message'),
    ]

    operations = [
    ]
