# Generated by Django 3.2.8 on 2021-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_merge_0002_login_0002_rename_pesan_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.IntegerField(),
        ),
    ]
